/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bfd9de",
        "on-tertiary-fixed-variant": "#6d6559",
        "on-secondary-fixed": "#2b4348",
        "primary-fixed": "#cde9da",
        "tertiary-dim": "#595246",
        "surface-container-highest": "#e1e3de",
        "on-secondary-container": "#3e565a",
        "primary-fixed-dim": "#bfdbcc",
        "on-primary": "#e5fff1",
        "surface-container-low": "#f4f4f0",
        "on-tertiary-fixed": "#4f493d",
        "on-tertiary-container": "#625b4f",
        "on-primary-fixed-variant": "#486155",
        "on-error": "#fff7f6",
        "inverse-primary": "#e1fdee",
        "surface-container-high": "#e7e9e4",
        "on-background": "#303330",
        "inverse-surface": "#0d0f0d",
        "surface-variant": "#e1e3de",
        "secondary-container": "#cde7ed",
        "on-tertiary": "#fff8f0",
        "surface-tint": "#4c6459",
        "tertiary": "#655e52",
        "tertiary-fixed-dim": "#efe4d4",
        "on-surface": "#303330",
        "outline": "#797b78",
        "on-secondary": "#ecfcff",
        "surface-container": "#eeeeea",
        "on-error-container": "#6e0a12",
        "secondary-fixed": "#cde7ed",
        "primary-dim": "#40584d",
        "tertiary-container": "#fdf2e2",
        "on-secondary-fixed-variant": "#475f64",
        "outline-variant": "#b0b3ae",
        "error-container": "#fa746f",
        "background": "#faf9f6",
        "surface-bright": "#faf9f6",
        "surface": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#2c443a",
        "secondary-dim": "#3f575c",
        "inverse-on-surface": "#9d9d9a",
        "tertiary-fixed": "#fdf2e2",
        "on-primary-container": "#3f574c",
        "error-dim": "#67040d",
        "secondary": "#4b6368",
        "error": "#a83836",
        "primary-container": "#cde9da",
        "surface-dim": "#d9dbd6",
        "on-surface-variant": "#5d605c",
        "primary": "#4c6459",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        fadeInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.7s ease-out forwards',
        'fade-in-left': 'fadeInLeft 0.7s ease-out forwards',
        'fade-in-right': 'fadeInRight 0.7s ease-out forwards',
        'scale-in': 'scaleIn 0.6s ease-out forwards',
      },
    },
  },
  plugins: [],
}
